# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Castra < Formula
  desc "Castra is a structured project management CLI for autonomous AI agents. It enforces role boundaries, audit trails, and sprint-driven workflows.
"
  homepage "https://github.com/amangsingh/castra"
  version "3.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amangsingh/castra/releases/download/v3.0.2/castra_3.0.2_darwin_amd64.tar.gz"
      sha256 "056e095bc3d407ae6ec620e6d34942fe185c4b7d09e9669b6993ffb3224cdc6c"

      define_method(:install) do
        bin.install "castra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amangsingh/castra/releases/download/v3.0.2/castra_3.0.2_darwin_arm64.tar.gz"
      sha256 "264ac177cfd60feaf3d2560b81da7c52ea3be4eab909c6c8489aa650dee83707"

      define_method(:install) do
        bin.install "castra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amangsingh/castra/releases/download/v3.0.2/castra_3.0.2_linux_amd64.tar.gz"
      sha256 "fb64f71911e24fd8986c1e91cb52f73721ac78d623e8f1712fc554bc9b189bc6"
      define_method(:install) do
        bin.install "castra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amangsingh/castra/releases/download/v3.0.2/castra_3.0.2_linux_arm64.tar.gz"
      sha256 "b1e5d77fe39573c0e1f3f7590b22f6767b050ac7665ca29086d93c2497fe5ed3"
      define_method(:install) do
        bin.install "castra"
      end
    end
  end

  def post_install
    ohai "Upgrading from v2.x? Run: castra db encrypt --sovereign"
    ohai "This migrates your workspace.db from integer PKs to UUIDv7 schema."
  end

  test do
    system "#{bin}/castra", "--help"
  end
end
