# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Castra < Formula
  desc "Castra is a structured project management CLI for autonomous AI agents. It enforces role boundaries, audit trails, and sprint-driven workflows.
"
  homepage "https://github.com/amangsingh/castra"
  version "4.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amangsingh/castra/releases/download/v4.3.0/castra_4.3.0_darwin_amd64.tar.gz"
      sha256 "efe0665ba752b6ed7841aa50a45d8b15ac4b853917c19db1b8213f55ba6de835"

      define_method(:install) do
        bin.install "castra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amangsingh/castra/releases/download/v4.3.0/castra_4.3.0_darwin_arm64.tar.gz"
      sha256 "3fec26b8ec1028defaaded9bc2650435fe339428e632168375a340c92d6df00f"

      define_method(:install) do
        bin.install "castra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amangsingh/castra/releases/download/v4.3.0/castra_4.3.0_linux_amd64.tar.gz"
      sha256 "d43b7273b2985db08d4c76f79c3d3cb0afea6b308dbef7cdb7b7e01584b3e3a1"
      define_method(:install) do
        bin.install "castra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amangsingh/castra/releases/download/v4.3.0/castra_4.3.0_linux_arm64.tar.gz"
      sha256 "a24459df39b89b10f9bec66d1b90cb309c7e797560a252d61f6d56c6975166db"
      define_method(:install) do
        bin.install "castra"
      end
    end
  end

  def post_install
    ohai "Upgrading from v2.x? Run: castra db encrypt --sovereign"
    ohai "This migrates your workspace.db from integer PKs to UUIDv7 schema."
  end

  test do
    system "#{bin}/castra", "--help"
  end
end
